/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/market/company-research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guided company research with independently cached financial sections. */
        get: operations["getCompanyResearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find securities by company name or ticker. */
        get: operations["searchCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/fund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Beginner "what is this?" explainer for an ETF, mutual fund, stock, index or cryptocurrency. */
        get: operations["getFund"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. No X-User-Id required. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["putProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/link-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPlaidLinkToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangePlaidPublicToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/sandbox-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dev only: creates a sandbox item with no Link UI. */
        post: operations["createPlaidSandboxLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHoldings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRisk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Takes 1 to 5 symbols; fewer or more is a 400. Reads shared snapshots without calling providers. Missing or expired histories queue an asynchronous refresh. A 200 may contain stale data; 202 contains available series while others are pending. Poll every 5 seconds while refreshing, for at most 2 minutes per refresh request. A missing snapshot with a failed refresh returns 502. No shared HTTP caching. */
        get: operations["getMarketHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Up to six publisher headlines from Yahoo Finance, cached for one hour (five minutes when the provider returned no articles, since that may be a transient failure). Omit symbols for market-wide stock news, where each article's symbol is an empty string. publishedAt is the provider's timestamp as given (Yahoo sends ISO 8601 in UTC); fetchedAt is API retrieval time. */
        get: operations["getMarketNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Up to ten stocks from FMP's active, daily gainers or daily losers list. Cached for one hour; fetchedAt is retrieval time, not quote time. Active retains provider ranking by trading activity. Price is in the security's quote currency; changePct is a fraction. */
        get: operations["getMarketMovers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/compare-companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Takes 2 to 4 symbols; fewer or more is a 400. */
        get: operations["compareCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/macro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMacro"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advisor/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postAdvisorChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advisor/retirement-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRetirementAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advisor/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAdvisorHistory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A presigned S3 PUT so audio never passes through API Gateway.
         * @description The Content-Type is part of the signature: the PUT to uploadUrl must send the same Content-Type header that was requested here, or S3 rejects it with 403.
         */
        post: operations["createVoiceUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speech-to-text on the uploaded key, then the same advisor as /advisor/chat. */
        post: operations["postVoiceTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice/speak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Text-to-speech into S3, returned as a presigned GET.
         * @description Accepts up to 5000 characters so a full advisor reply can be sent as-is; it is trimmed to about 2000 characters at a sentence boundary before speech.
         */
        post: operations["postVoiceSpeak"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResearchProfile: {
            name: string;
            description: string | null;
            sector: string | null;
            industry: string | null;
            currency: string | null;
            isFund: boolean;
            /** @description Volatility relative to the market (1 moves with it). Data only. */
            beta: number | null;
            /** @description Market value of all shares, in the profile currency. Null when missing or not positive. */
            marketCap: number | null;
            /**
             * Format: date
             * @description Next scheduled earnings report on or after today (UTC, checked on every response, including cached ones); null for funds or when unknown.
             */
            nextEarningsDate: string | null;
        } | null;
        AnnualIncome: {
            /** Format: date */
            date: string;
            year: string;
            currency: string | null;
            revenue: number | null;
            costOfRevenue: number | null;
            grossProfit: number | null;
            operatingIncome: number | null;
            netIncome: number | null;
            epsDiluted: number | null;
        };
        ResearchValuation: {
            pe: number | null;
            eps: number | null;
            ps: number | null;
            /** @description Trailing-12-month dividend yield as a FRACTION (0.0045 = 0.45%). 0 means the provider reports no dividend. Null means unknown - the value is missing, negative or implausible (over 0.25) - and must not be read as "no dividend". */
            dividendYield: number | null;
        } | null;
        AnnualValuation: {
            /** Format: date */
            date: string;
            year: string;
            pe: number | null;
        };
        ResearchSource: {
            /** @enum {string} */
            section: "profile" | "income" | "valuation" | "history";
            provider: string;
            /** Format: date-time */
            fetchedAt: string;
            stale: boolean;
        };
        CompanyResearch: {
            symbol: string;
            profile: components["schemas"]["ResearchProfile"];
            income: components["schemas"]["AnnualIncome"][];
            valuation: components["schemas"]["ResearchValuation"];
            history: components["schemas"]["AnnualValuation"][];
            unavailable: ("profile" | "income" | "valuation" | "history")[];
            sources: components["schemas"]["ResearchSource"][];
        };
        CompanySearch: {
            results: {
                symbol: string;
                name: string;
                exchange: string | null;
            }[];
            stale: boolean;
        };
        FundHolding: {
            symbol: string | null;
            name: string;
            weight: number;
        };
        Fund: {
            symbol: string;
            name: string;
            /** @enum {string} */
            kind: "etf" | "mutual_fund" | "stock" | "index" | "crypto" | "other";
            isIndexFund: boolean;
            leveraged: boolean;
            tracks: string | null;
            expenseRatio: number | null;
            topHoldings: components["schemas"]["FundHolding"][];
            fundFamily: string | null;
            category: string | null;
            sector: string | null;
            summary: string;
            /** @enum {string} */
            summarySource: "model" | "template";
            /** Format: date */
            asOf: string;
            stale: boolean;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "VALIDATION" | "NOT_FOUND" | "NOT_LINKED" | "UPSTREAM_UNAVAILABLE" | "INTERNAL";
                message: string;
                requestId: string | null;
            };
        };
        Profile: {
            age: number;
            /** @enum {string} */
            horizon: "short" | "medium" | "long";
            goals: string[];
            /** @enum {string} */
            riskTolerance: "low" | "medium" | "high";
        };
        Holding: {
            symbol: string;
            name: string;
            type: string;
            quantity: number;
            price: number;
            value: number;
            weight: number;
        };
        Holdings: {
            asOf: string;
            totalValue: number;
            holdings: components["schemas"]["Holding"][];
            stale?: boolean;
        };
        Risk: {
            score: number;
            label: string;
            factors: {
                name: string;
                detail: string;
            }[];
            summary: string;
        };
        HistorySeries: {
            symbol: string;
            points: {
                date: string;
                close: number;
            }[];
            returnPct: number;
            volatility: number;
        };
        History: {
            series: components["schemas"]["HistorySeries"][];
            stale?: boolean;
            /** @description At least one requested symbol has a refresh queued or running. */
            refreshing?: boolean;
            refresh?: {
                symbol: string;
                /** @enum {string} */
                status: "ready" | "pending" | "failed";
                /**
                 * Format: date-time
                 * @description Snapshot retrieval time, not the last price observation date.
                 */
                fetchedAt: string | null;
                /**
                 * Format: date-time
                 * @description Start of this refresh; bounds automatic client polling.
                 */
                requestedAt: string | null;
            }[];
        };
        MarketNews: {
            articles: components["schemas"]["NewsArticle"][];
            symbols: string[];
            /** @enum {string} */
            source: "Yahoo Finance";
            /** Format: date-time */
            fetchedAt: string;
            stale: boolean;
        };
        NewsArticle: {
            title: string;
            /** Format: uri */
            url: string;
            image: string | null;
            publisher: string;
            publishedAt: string;
            symbol: string;
        };
        MarketMovers: {
            /** @enum {string} */
            category: "active" | "gainers" | "losers";
            stocks: components["schemas"]["MarketStock"][];
            /** Format: date-time */
            fetchedAt: string;
            /** @enum {string} */
            source: "FMP";
            stale: boolean;
        };
        MarketStock: {
            symbol: string;
            name: string;
            price: number;
            /** @description Daily percentage change expressed as a fraction (0.025 means 2.5%). */
            changePct: number;
            exchange: string;
        };
        Company: {
            symbol: string;
            /** @description Trailing P/E; null for nonpositive ratios or known nonpositive earnings. */
            pe: number | null;
            ps: number | null;
            grossMargin: number | null;
            revenueGrowth: number | null;
            /** @description Trailing earnings per share. Currency is not supplied; do not assume USD. */
            epsTTM: number | null;
            /** @description Free cash flow per share. Currency is not supplied; do not assume USD. */
            fcfPerShare: number | null;
            debtToEquity: number | null;
        };
        Companies: {
            companies: components["schemas"]["Company"][];
            notes: string;
            stale?: boolean;
        };
        Macro: {
            fedFunds: number | null;
            cpiYoY: number | null;
            unemployment: number | null;
            wageGrowth: number | null;
            tenYear: number | null;
            asOf: string | null;
            summary: string;
            stale?: boolean;
        };
        Template: {
            id: string;
            name: string;
            description: string;
            allocations: {
                asset: string;
                weight: number;
            }[];
            source?: string;
        };
        ChatReply: {
            /** @description A short reply, at most about 120 words. May use a markdown subset: **bold** for key terms, "- " bullets, "1." numbered lists, and (only when comparing 2-3 options) a GitHub-flavored markdown table of up to 3 columns. Never contains headings ("#"). */
            reply: string;
            disclaimer: string;
        };
        RetirementAccounts: {
            accounts: {
                id: string;
                name: string;
                taxTreatment: string;
                contributionLimit: string;
                bestFor: string;
                source?: string;
            }[];
            personalized: string;
        };
        UploadUrl: {
            uploadUrl: string;
            key: string;
            expiresIn: number;
        };
        VoiceTurn: {
            transcript: string;
            /** @description A short reply meant to be read aloud, about 60 words of plain text: no markdown, no headings, no lists, no tables. */
            reply: string;
            disclaimer: string;
        };
        Speech: {
            audioUrl: string;
            expiresIn: number;
        };
    };
    responses: {
        /** @description The request failed validation (e.g. a missing/invalid X-User-Id, or a bad body/query param). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION",
                 *         "message": "X-User-Id header is required and must be a UUID.",
                 *         "requestId": "9a1e6b2e-0000-4c00-8000-000000000001"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The user has no linked Plaid item yet. */
        NotLinked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_LINKED",
                 *         "message": "No linked account. Send the user to Plaid Link.",
                 *         "requestId": "9a1e6b2e-0000-4c00-8000-000000000002"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource does not exist (e.g. no profile saved yet). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "No profile yet",
                 *         "requestId": "9a1e6b2e-0000-4c00-8000-000000000004"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A data provider is down. */
        Upstream: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UPSTREAM_UNAVAILABLE",
                 *         "message": "The data provider is temporarily unavailable. Please retry.",
                 *         "requestId": "9a1e6b2e-0000-4c00-8000-000000000003"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The user's id. Required on every route except /health. */
        UserId: string;
        /**
         * @description Comma-separated ticker symbols.
         * @example AMD,NVDA
         */
        Symbols: string;
        Range: "1y" | "5y" | "10y";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCompanyResearch: {
        parameters: {
            query: {
                symbol: string;
            };
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available provider data. Missing values are null; unavailable sections are explicit. Example financial figures are illustrative. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "symbol": "AAPL",
                     *       "profile": {
                     *         "name": "Example company (illustrative data)",
                     *         "description": "An example business selling products and services.",
                     *         "sector": "Technology",
                     *         "industry": "Consumer electronics",
                     *         "currency": "USD",
                     *         "isFund": false,
                     *         "beta": 1.1,
                     *         "marketCap": 3400000000000,
                     *         "nextEarningsDate": "2026-10-29"
                     *       },
                     *       "income": [
                     *         {
                     *           "date": "2025-12-31",
                     *           "year": "2025",
                     *           "currency": "USD",
                     *           "revenue": 100000000,
                     *           "costOfRevenue": 60000000,
                     *           "grossProfit": 40000000,
                     *           "operatingIncome": 24000000,
                     *           "netIncome": 20000000,
                     *           "epsDiluted": 5
                     *         },
                     *         {
                     *           "date": "2024-12-31",
                     *           "year": "2024",
                     *           "currency": "USD",
                     *           "revenue": 90000000,
                     *           "costOfRevenue": 54000000,
                     *           "grossProfit": 36000000,
                     *           "operatingIncome": 21600000,
                     *           "netIncome": 18000000,
                     *           "epsDiluted": 4.5
                     *         },
                     *         {
                     *           "date": "2023-12-31",
                     *           "year": "2023",
                     *           "currency": "USD",
                     *           "revenue": 85000000,
                     *           "costOfRevenue": 51000000,
                     *           "grossProfit": 34000000,
                     *           "operatingIncome": 19200000,
                     *           "netIncome": 16000000,
                     *           "epsDiluted": 4
                     *         }
                     *       ],
                     *       "valuation": {
                     *         "pe": 20,
                     *         "eps": 5,
                     *         "ps": 4,
                     *         "dividendYield": 0.0045
                     *       },
                     *       "history": [
                     *         {
                     *           "date": "2025-12-31",
                     *           "year": "2025",
                     *           "pe": 20
                     *         },
                     *         {
                     *           "date": "2024-12-31",
                     *           "year": "2024",
                     *           "pe": 18
                     *         },
                     *         {
                     *           "date": "2023-12-31",
                     *           "year": "2023",
                     *           "pe": 22
                     *         }
                     *       ],
                     *       "unavailable": [],
                     *       "sources": [
                     *         {
                     *           "section": "profile",
                     *           "provider": "FMP",
                     *           "fetchedAt": "2026-09-26T12:00:00Z",
                     *           "stale": false
                     *         },
                     *         {
                     *           "section": "income",
                     *           "provider": "FMP",
                     *           "fetchedAt": "2026-09-26T12:00:00Z",
                     *           "stale": false
                     *         },
                     *         {
                     *           "section": "valuation",
                     *           "provider": "FMP",
                     *           "fetchedAt": "2026-09-26T12:00:00Z",
                     *           "stale": false
                     *         },
                     *         {
                     *           "section": "history",
                     *           "provider": "FMP",
                     *           "fetchedAt": "2026-09-26T12:00:00Z",
                     *           "stale": false
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["CompanyResearch"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    searchCompanies: {
        parameters: {
            query: {
                query: string;
            };
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available provider data. Missing values are null; unavailable sections are explicit. Example financial figures are illustrative. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "results": [
                     *         {
                     *           "symbol": "AAPL",
                     *           "name": "Apple Inc.",
                     *           "exchange": "NASDAQ"
                     *         }
                     *       ],
                     *       "stale": false
                     *     }
                     */
                    "application/json": components["schemas"]["CompanySearch"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    getFund: {
        parameters: {
            query: {
                symbol: string;
            };
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every number (expenseRatio, topHoldings weights) comes from the data provider, never the model. summary is a one-sentence beginner explanation; summarySource says whether it was rewritten by the model or is the plain template (always template for a leveraged fund, an index, a cryptocurrency, or an unrecognized kind). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "symbol": "VOO",
                     *       "name": "Vanguard S&P 500 ETF",
                     *       "kind": "etf",
                     *       "isIndexFund": true,
                     *       "leveraged": false,
                     *       "tracks": "Standard & Poor's 500 Index",
                     *       "expenseRatio": 0.0003,
                     *       "topHoldings": [
                     *         {
                     *           "symbol": "NVDA",
                     *           "name": "NVIDIA Corp",
                     *           "weight": 0.08082
                     *         },
                     *         {
                     *           "symbol": "AAPL",
                     *           "name": "Apple Inc",
                     *           "weight": 0.070339
                     *         },
                     *         {
                     *           "symbol": "MSFT",
                     *           "name": "Microsoft Corp",
                     *           "weight": 0.056958
                     *         }
                     *       ],
                     *       "fundFamily": "Vanguard",
                     *       "category": "Large Blend",
                     *       "sector": null,
                     *       "summary": "This fund spreads your money across hundreds of well-known American companies in a single investment.",
                     *       "summarySource": "model",
                     *       "asOf": "2026-09-27",
                     *       "stale": false
                     *     }
                     */
                    "application/json": components["schemas"]["Fund"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "1.0.0"
                     *     }
                     */
                    "application/json": {
                        status: string;
                        version: string;
                    };
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "age": 24,
                     *       "horizon": "long",
                     *       "goals": [
                     *         "retire early",
                     *         "buy a house"
                     *       ],
                     *       "riskTolerance": "medium"
                     *     }
                     */
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    putProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "age": 24,
                 *       "horizon": "long",
                 *       "goals": [
                 *         "retire early",
                 *         "buy a house"
                 *       ],
                 *       "riskTolerance": "medium"
                 *     }
                 */
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description The saved profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "age": 24,
                     *       "horizon": "long",
                     *       "goals": [
                     *         "retire early",
                     *         "buy a house"
                     *       ],
                     *       "riskTolerance": "medium"
                     *     }
                     */
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createPlaidLinkToken: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A Plaid Link token for the frontend to open Link with. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "linkToken": "link-sandbox-11111111-2222-3333-4444-555555555555"
                     *     }
                     */
                    "application/json": {
                        linkToken: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    exchangePlaidPublicToken: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicToken: string;
                };
            };
        };
        responses: {
            /** @description The Plaid item created from the public token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "itemId": "item-sandbox-66666666-7777-8888-9999-000000000000"
                     *     }
                     */
                    "application/json": {
                        itemId: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    createPlaidSandboxLink: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Plaid item created directly in the sandbox. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "itemId": "item-sandbox-66666666-7777-8888-9999-000000000000"
                     *     }
                     */
                    "application/json": {
                        itemId: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    getHoldings: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's normalized holdings, cached for 1h. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "asOf": "2026-09-26T00:00:00+00:00",
                     *       "totalValue": 10000,
                     *       "holdings": [
                     *         {
                     *           "symbol": "VTI",
                     *           "name": "Vanguard Total Stock Market ETF",
                     *           "type": "etf",
                     *           "quantity": 20,
                     *           "price": 250,
                     *           "value": 5000,
                     *           "weight": 0.5
                     *         },
                     *         {
                     *           "symbol": "AAPL",
                     *           "name": "Apple Inc.",
                     *           "type": "equity",
                     *           "quantity": 10,
                     *           "price": 200,
                     *           "value": 2000,
                     *           "weight": 0.2
                     *         },
                     *         {
                     *           "symbol": "BND",
                     *           "name": "Vanguard Total Bond Market ETF",
                     *           "type": "fixed income",
                     *           "quantity": 300,
                     *           "price": 10,
                     *           "value": 3000,
                     *           "weight": 0.3
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["Holdings"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["NotLinked"];
            502: components["responses"]["Upstream"];
        };
    };
    getRisk: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deterministic 0-100 risk score. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "score": 58,
                     *       "label": "Moderate",
                     *       "factors": [
                     *         {
                     *           "name": "Concentration",
                     *           "detail": "Your largest position (VTI) is 50% of your portfolio."
                     *         },
                     *         {
                     *           "name": "Asset mix",
                     *           "detail": "70% equity/ETF, 30% fixed income."
                     *         },
                     *         {
                     *           "name": "Horizon",
                     *           "detail": "A long time horizon supports a bit more risk."
                     *         }
                     *       ],
                     *       "summary": "A moderate risk profile balancing growth and stability."
                     *     }
                     */
                    "application/json": components["schemas"]["Risk"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["NotLinked"];
            502: components["responses"]["Upstream"];
        };
    };
    getMarketHistory: {
        parameters: {
            query: {
                /**
                 * @description Comma-separated ticker symbols.
                 * @example AMD,NVDA
                 */
                symbols: components["parameters"]["Symbols"];
                range?: components["parameters"]["Range"];
            };
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price history and computed return/volatility per symbol. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "series": [
                     *         {
                     *           "symbol": "VOO",
                     *           "points": [
                     *             {
                     *               "date": "2026-07-01",
                     *               "close": 520.12
                     *             },
                     *             {
                     *               "date": "2026-08-01",
                     *               "close": 531.4
                     *             },
                     *             {
                     *               "date": "2026-09-01",
                     *               "close": 545.87
                     *             }
                     *           ],
                     *           "returnPct": 0.0494,
                     *           "volatility": 0.132
                     *         },
                     *         {
                     *           "symbol": "QQQ",
                     *           "points": [
                     *             {
                     *               "date": "2026-07-01",
                     *               "close": 480.55
                     *             },
                     *             {
                     *               "date": "2026-08-01",
                     *               "close": 470.2
                     *             },
                     *             {
                     *               "date": "2026-09-01",
                     *               "close": 492.33
                     *             }
                     *           ],
                     *           "returnPct": 0.0245,
                     *           "volatility": 0.198
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description One or more histories are not cached yet; refresh is pending. */
            202: {
                headers: {
                    "Retry-After"?: 5;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "series": [],
                     *       "stale": false,
                     *       "refreshing": true,
                     *       "refresh": [
                     *         {
                     *           "symbol": "VOO",
                     *           "status": "pending",
                     *           "fetchedAt": null,
                     *           "requestedAt": "2026-09-26T12:00:00+00:00"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["History"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    getMarketNews: {
        parameters: {
            query?: {
                /** @description One or two comma-separated ticker symbols. */
                symbols?: string;
            };
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description News headlines with publisher links and optional images. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "articles": [
                     *         {
                     *           "title": "Example headline: investors look ahead to the next earnings release",
                     *           "url": "https://example.com/market-news/earnings",
                     *           "image": null,
                     *           "publisher": "Example publisher",
                     *           "publishedAt": "2026-09-25T15:00:00Z",
                     *           "symbol": ""
                     *         },
                     *         {
                     *           "title": "Example headline: new products draw attention across the technology sector",
                     *           "url": "https://example.com/market-news/products",
                     *           "image": null,
                     *           "publisher": "Example publisher",
                     *           "publishedAt": "2026-09-25T13:00:00Z",
                     *           "symbol": ""
                     *         },
                     *         {
                     *           "title": "Example headline: market participants assess the latest economic data",
                     *           "url": "https://example.com/market-news/economy",
                     *           "image": null,
                     *           "publisher": "Example publisher",
                     *           "publishedAt": "2026-09-25T12:00:00Z",
                     *           "symbol": ""
                     *         }
                     *       ],
                     *       "symbols": [],
                     *       "source": "Yahoo Finance",
                     *       "fetchedAt": "2026-09-25T20:00:00Z",
                     *       "stale": false
                     *     }
                     */
                    "application/json": components["schemas"]["MarketNews"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    getMarketMovers: {
        parameters: {
            query?: {
                category?: "active" | "gainers" | "losers";
            };
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A ranked market discovery list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "category": "active",
                     *       "stocks": [
                     *         {
                     *           "symbol": "NVDA",
                     *           "name": "NVIDIA Corporation",
                     *           "price": 140.52,
                     *           "changePct": 0.0234,
                     *           "exchange": "NASDAQ"
                     *         },
                     *         {
                     *           "symbol": "TSLA",
                     *           "name": "Tesla Inc.",
                     *           "price": 250.12,
                     *           "changePct": -0.0121,
                     *           "exchange": "NASDAQ"
                     *         },
                     *         {
                     *           "symbol": "AAPL",
                     *           "name": "Apple Inc.",
                     *           "price": 225.4,
                     *           "changePct": 0.0056,
                     *           "exchange": "NASDAQ"
                     *         },
                     *         {
                     *           "symbol": "AMD",
                     *           "name": "Advanced Micro Devices Inc.",
                     *           "price": 160.3,
                     *           "changePct": 0.0182,
                     *           "exchange": "NASDAQ"
                     *         },
                     *         {
                     *           "symbol": "INTC",
                     *           "name": "Intel Corporation",
                     *           "price": 22.5,
                     *           "changePct": -0.024,
                     *           "exchange": "NASDAQ"
                     *         },
                     *         {
                     *           "symbol": "PLTR",
                     *           "name": "Palantir Technologies Inc.",
                     *           "price": 35.2,
                     *           "changePct": 0.0345,
                     *           "exchange": "NASDAQ"
                     *         },
                     *         {
                     *           "symbol": "AMZN",
                     *           "name": "Amazon.com Inc.",
                     *           "price": 190.8,
                     *           "changePct": 0.0098,
                     *           "exchange": "NASDAQ"
                     *         },
                     *         {
                     *           "symbol": "F",
                     *           "name": "Ford Motor Company",
                     *           "price": 10.7,
                     *           "changePct": -0.0074,
                     *           "exchange": "NYSE"
                     *         },
                     *         {
                     *           "symbol": "SOFI",
                     *           "name": "SoFi Technologies Inc.",
                     *           "price": 8.3,
                     *           "changePct": 0.0412,
                     *           "exchange": "NASDAQ"
                     *         },
                     *         {
                     *           "symbol": "MSFT",
                     *           "name": "Microsoft Corporation",
                     *           "price": 430.6,
                     *           "changePct": 0.0067,
                     *           "exchange": "NASDAQ"
                     *         }
                     *       ],
                     *       "fetchedAt": "2026-09-25T20:00:00Z",
                     *       "source": "FMP",
                     *       "stale": false
                     *     }
                     */
                    "application/json": components["schemas"]["MarketMovers"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    compareCompanies: {
        parameters: {
            query: {
                /**
                 * @description Comma-separated ticker symbols.
                 * @example AMD,NVDA
                 */
                symbols: components["parameters"]["Symbols"];
            };
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized fundamental ratios per symbol. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "companies": [
                     *         {
                     *           "symbol": "AMD",
                     *           "pe": 95.1,
                     *           "ps": 11.2,
                     *           "grossMargin": 0.532,
                     *           "revenueGrowth": 0.343,
                     *           "epsTTM": 1.9,
                     *           "fcfPerShare": 4.1,
                     *           "debtToEquity": 0.06
                     *         },
                     *         {
                     *           "symbol": "NVDA",
                     *           "pe": 65.4,
                     *           "ps": 28.7,
                     *           "grossMargin": 0.75,
                     *           "revenueGrowth": 0.2,
                     *           "epsTTM": 2.94,
                     *           "fcfPerShare": 2.6,
                     *           "debtToEquity": 0.12
                     *         }
                     *       ],
                     *       "notes": "Ratios are trailing-twelve-month figures from provider data and may lag the latest quarter."
                     *     }
                     */
                    "application/json": components["schemas"]["Companies"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    getMacro: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest FRED macro snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "fedFunds": 4.33,
                     *       "cpiYoY": 2.9,
                     *       "unemployment": 4.2,
                     *       "wageGrowth": 3.8,
                     *       "tenYear": 4.1,
                     *       "asOf": "2026-08-01",
                     *       "summary": "Fed funds 4.33%, inflation 2.9% YoY, unemployment 4.2%, wages +3.8% YoY, 10-year Treasury 4.1%."
                     *     }
                     */
                    "application/json": components["schemas"]["Macro"];
                };
            };
            502: components["responses"]["Upstream"];
        };
    };
    getTemplates: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bundled portfolio templates (not user-specific). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "three-fund",
                     *         "name": "Bogleheads three-fund",
                     *         "description": "US stocks, international stocks and US bonds in one example weighting; the Bogleheads wiki treats the exact split as a matter of personal risk tolerance.",
                     *         "allocations": [
                     *           {
                     *             "asset": "VTI",
                     *             "weight": 0.5
                     *           },
                     *           {
                     *             "asset": "VXUS",
                     *             "weight": 0.3
                     *           },
                     *           {
                     *             "asset": "BND",
                     *             "weight": 0.2
                     *           }
                     *         ],
                     *         "source": "https://www.bogleheads.org/wiki/Three-fund_portfolio"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Template"][];
                };
            };
        };
    };
    postAdvisorChat: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                };
            };
        };
        responses: {
            /** @description The advisor's reply, grounded in the user's real numbers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reply": "At 24, a Roth IRA is worth considering since you're likely in a lower tax bracket now than you will be in retirement.",
                     *       "disclaimer": "ClearVest provides educational information, not financial advice. Consider a licensed professional before making investment decisions."
                     *     }
                     */
                    "application/json": components["schemas"]["ChatReply"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getRetirementAccounts: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Static, sourced retirement account facts plus a personalized note. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "accounts": [
                     *         {
                     *           "id": "traditional-401k",
                     *           "name": "Traditional 401(k)",
                     *           "taxTreatment": "Pre-tax contributions, taxed on withdrawal.",
                     *           "contributionLimit": "$24,500 employee deferral (2026); $8,000 catch-up at 50+",
                     *           "bestFor": "Higher earners now who expect a lower tax rate in retirement.",
                     *           "source": "https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits"
                     *         },
                     *         {
                     *           "id": "roth-401k",
                     *           "name": "Roth 401(k)",
                     *           "taxTreatment": "After-tax contributions, qualified withdrawals tax-free.",
                     *           "contributionLimit": "$24,500 employee deferral (2026); $8,000 catch-up at 50+",
                     *           "bestFor": "Early-career earners who expect higher taxes later.",
                     *           "source": "https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-topics-401k-and-profit-sharing-plan-contribution-limits"
                     *         },
                     *         {
                     *           "id": "roth-ira",
                     *           "name": "Roth IRA",
                     *           "taxTreatment": "After-tax contributions, qualified withdrawals tax-free.",
                     *           "contributionLimit": "$7,500 (2026); $1,100 catch-up at 50+; income limits apply",
                     *           "bestFor": "Anyone under the income limit who wants tax-free growth and flexible access to contributions.",
                     *           "source": "https://www.irs.gov/retirement-plans/roth-iras"
                     *         },
                     *         {
                     *           "id": "tsp",
                     *           "name": "Thrift Savings Plan (TSP)",
                     *           "taxTreatment": "Federal employees and uniformed services; traditional or Roth; very low fees.",
                     *           "contributionLimit": "$24,500 employee deferral (2026); $8,000 catch-up at 50+",
                     *           "bestFor": "Federal employees and service members seeking low-cost retirement savings.",
                     *           "source": "https://www.tsp.gov/making-contributions/contribution-limits/"
                     *         }
                     *       ],
                     *       "personalized": "At 24, Roth accounts often make more sense since you're likely in a lower tax bracket now than you will be later."
                     *     }
                     */
                    "application/json": components["schemas"]["RetirementAccounts"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteAdvisorHistory: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat history cleared. No body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createVoiceUploadUrl: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    contentType: "audio/webm" | "audio/mp4" | "audio/mpeg" | "audio/wav" | "audio/ogg";
                };
            };
        };
        responses: {
            /** @description A presigned PUT URL and the key the recording will land at. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "uploadUrl": "https://clearvest-audio.s3.us-east-1.amazonaws.com/audio/in/11111111-1111-1111-1111-111111111111/22222222-2222-2222-2222-222222222222?X-Amz-Signature=example",
                     *       "key": "audio/in/11111111-1111-1111-1111-111111111111/22222222-2222-2222-2222-222222222222",
                     *       "expiresIn": 900
                     *     }
                     */
                    "application/json": components["schemas"]["UploadUrl"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    postVoiceTurn: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    key: string;
                };
            };
        };
        responses: {
            /** @description The transcript and the advisor's reply. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "transcript": "What's a good retirement account for someone my age?",
                     *       "reply": "At 24, a Roth IRA is worth considering since you're likely in a lower tax bracket now than you will be in retirement.",
                     *       "disclaimer": "ClearVest provides educational information, not financial advice. Consider a licensed professional before making investment decisions."
                     *     }
                     */
                    "application/json": components["schemas"]["VoiceTurn"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
    postVoiceSpeak: {
        parameters: {
            query?: never;
            header: {
                /** @description The user's id. Required on every route except /health. */
                "X-User-Id": components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description A presigned GET URL for the synthesized mp3. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "audioUrl": "https://clearvest-audio.s3.us-east-1.amazonaws.com/audio/out/11111111-1111-1111-1111-111111111111/33333333-3333-3333-3333-333333333333.mp3?X-Amz-Signature=example",
                     *       "expiresIn": 900
                     *     }
                     */
                    "application/json": components["schemas"]["Speech"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["Upstream"];
        };
    };
}
