const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const yaml = require('js-yaml');
const previewUrl = process.env.CLEARVEST_PREVIEW_URL || 'http://127.0.0.1:5173';
const assert = require('node:assert/strict');
// Start the Vite dev server before running. All API calls use contract examples.
const contract = yaml.load(fs.readFileSync(path.resolve(__dirname, '../../docs/api/openapi.yaml'), 'utf8'));
const output = path.resolve(__dirname, '../node_modules/.cache/clearvest-review');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined, headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1100},colorScheme:'dark',timezoneId:'America/New_York'});
  await context.addInitScript(() => localStorage.setItem('cv-theme','dark'));
  const errors=[]; const requests=[]; const plaidRequests=[];
  context.on('request', request=>{if(request.url().startsWith('https://cdn.plaid.com/')) plaidRequests.push(request.url())});
  let historyMode='ok'; let profileMode='ok'; let holdingsMode='ok';
  let profileSaveMode='ok'; const profileWrites=[];
  await context.route('http://127.0.0.1:4010/**', async route => {
    const url=new URL(route.request().url()); requests.push(url.pathname+url.search);
    const op=contract.paths[url.pathname]?.[route.request().method().toLowerCase()];
    let status=200;
    let body=structuredClone(op?.responses?.['200']?.content?.['application/json']?.example ?? {});
    if(url.pathname==='/market/history') {
      if(historyMode==='error') {status=502;body={error:{code:'UPSTREAM_UNAVAILABLE',message:'Unavailable',requestId:null}};}
      else if(historyMode==='empty') body={series:[]};
      else body={...body,series:body.series.filter(s=>s.symbol===url.searchParams.get('symbols')),stale:historyMode==='stale'};
    }
    if(url.pathname==='/profile' && route.request().method()==='PUT') {
      profileWrites.push(route.request().postDataJSON());
      if(profileSaveMode==='error') {status=500;body={error:{code:'INTERNAL',message:'Unable to save',requestId:null}};}
      else body=route.request().postDataJSON();
    }
    if(url.pathname==='/plaid/exchange') holdingsMode='ok';
    if(url.pathname==='/profile' && profileMode==='new') {status=404;body={error:{code:'NOT_FOUND',message:'No profile',requestId:null}};}
    if(url.pathname==='/portfolio/holdings' && holdingsMode==='empty') body={...body,holdings:[],totalValue:0};
    if(url.pathname==='/portfolio/holdings' && holdingsMode==='unlinked') {status=409;body={error:{code:'NOT_LINKED',message:'Link account',requestId:null}};}
    await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body),headers:{'access-control-allow-origin':'*'}});
  });
  const page=await context.newPage(); page.on('pageerror', e=>{errors.push(e.message);console.error('Page error on '+page.url(),e.stack)});
  await page.clock.install({time:new Date('2026-09-26T11:59:30-04:00')});
  await page.goto(previewUrl + '/portfolio');
  await page.getByRole('group',{name:'VOO interactive price chart'}).waitFor();
  await page.evaluate(()=>document.fonts.ready);
  for(const weight of [400,600,700]) {
    assert(await page.evaluate(async weight => {const faces=await document.fonts.load(`${weight} 16px SamsungOne`);return faces.some(face=>face.status==='loaded'&&face.family==='SamsungOne')},weight),`SamsungOne ${weight} must load from bundled webfont`);
  }
  assert(await page.locator('img[src="/images/coastal-morning.webp"]').evaluate(img=>img.complete&&img.naturalWidth>0));
  assert.equal(await page.locator('a[href*="utm_medium=lwc-link"]').count(),0,'No in-chart TradingView logo');
  assert.equal(await page.getByRole('link',{name:'TradingView Lightweight Charts™'}).count(),1,'Footer attribution remains');
  assert.equal(await page.getByRole('button',{name:/greeting rotation/}).count(),0,'Greeting has no pause/resume controls');
  assert(!(await page.locator('h1').innerText()).includes('Welcome back'),'No returning-user phrase');
  await page.getByText('Good morning.',{exact:true}).waitFor();
  await page.clock.fastForward(8000);
  await page.getByText('Good morning.',{exact:true}).waitFor();
  await page.clock.fastForward(60000);
  await page.getByText('Good afternoon.',{exact:true}).waitFor();
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.clock.setSystemTime(new Date('2026-09-26T17:59:30-04:00'));
  await page.clock.fastForward(60000);
  await page.getByText('Good evening.',{exact:true}).waitFor();
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.clock.resume();
  await page.getByRole('button',{name:'Hide portfolio values'}).click();
  assert.equal(await page.locator('[data-private-value]').innerText(),'••••');
  assert(!await page.locator('main').innerText().then(text=>text.includes('$10,000')||text.includes('$5,000')),'Amounts are removed from DOM text');
  await page.reload(); await page.getByRole('button',{name:'Show portfolio values'}).waitFor();
  assert.equal(await page.locator('[data-private-value]').innerText(),'••••','Privacy persists');
  await page.getByRole('button',{name:'Show portfolio values'}).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(245, 247, 250)');
  await page.screenshot({path:path.join(output,'portfolio-desktop.png'),fullPage:true});
  await page.getByText('What shapes this score', {exact:true}).click();
  await page.getByText('Concentration', {exact:true}).waitFor();
  const chart=page.getByRole('group',{name:'VOO interactive price chart'});
  await chart.focus(); await page.keyboard.press('ArrowLeft');
  await page.getByText('Aug 1, 2026 · 531.40',{exact:true}).waitFor();
  await page.getByRole('button',{name:'View as table',exact:true}).click();
  await page.getByRole('table',{name:'VOO closing prices'}).waitFor();
  await page.getByRole('button',{name:'View chart',exact:true}).click();
  await Promise.all([page.waitForResponse(r=>r.url().includes('range=5y')),page.getByRole('button',{name:'5Y',exact:true}).click()]);
  assert(requests.some(x=>x.includes('symbols=VOO')&&x.includes('range=5y')));
  const holdings=contract.paths['/portfolio/holdings'].get.responses['200'].content['application/json'].example.holdings;
  await page.getByRole('textbox',{name:'Filter holdings'}).fill('nomatch');
  await page.getByText('No holdings match your search. Try a name or symbol.').waitFor();
  await page.getByRole('textbox',{name:'Filter holdings'}).fill(holdings[0].symbol);
  await page.getByRole('link',{name:holdings[0].symbol,exact:true}).first().click();
  assert(new URL(page.url()).searchParams.get('symbol')===holdings[0].symbol);
  await page.goto(previewUrl + '/markets?symbol=QQQ');
  await page.getByRole('group',{name:'QQQ interactive price chart'}).waitFor();
  await page.getByRole('textbox',{name:'Research a ticker symbol'}).fill('bad ticker');
  await page.getByRole('button',{name:'Research symbol',exact:true}).click();
  await page.getByRole('alert').waitFor();
  await page.screenshot({path:path.join(output,'markets-desktop.png'),fullPage:true});
  historyMode='error'; await page.reload();
  await page.getByRole('button',{name:'Retry',exact:true}).waitFor();
  await page.getByRole('heading',{name:'Top 10 most active',exact:true}).waitFor();
  historyMode='ok'; await page.getByRole('button',{name:'Retry',exact:true}).click();
  await page.getByRole('group',{name:'QQQ interactive price chart'}).waitFor();
  historyMode='stale'; await page.reload(); await page.getByText('Cached data',{exact:true}).waitFor();
  historyMode='empty'; await page.reload(); await page.getByText('No price history was returned for QQQ. Try another ticker.').waitFor();
  historyMode='ok';
  for(const width of [390,320,768]) {
    await page.setViewportSize({width,height:900}); await page.goto(previewUrl + '/portfolio');
    await page.getByRole('group',{name:'VOO interactive price chart'}).waitFor();
    const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));
    if(dimensions.scroll>dimensions.width) console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth).map(e=>[e.tagName,e.className,e.getBoundingClientRect().right])));
    assert(dimensions.scroll<=dimensions.width,`overflow at ${width}: ${JSON.stringify(dimensions)}`);
    if(width===390) await page.screenshot({path:path.join(output,'portfolio-mobile.png'),fullPage:true});
  }
  await page.setViewportSize({width:1440,height:1100});
  await page.goto(previewUrl + '/advisor?q=Explain%20my%20holdings');
  await page.getByRole('textbox').waitFor();
  assert.equal(await page.getByRole('textbox').inputValue(),'Explain my holdings');
  assert(!requests.some(x=>x.startsWith('/advisor/chat')),'Prefilled question must not auto-send');
  const contextRail=page.getByRole('complementary',{name:'What the advisor sees'});
  await contextRail.getByRole('meter',{name:'Portfolio risk score'}).waitFor();
  assert(await contextRail.locator('details').evaluate(el=>el.open),'Context starts expanded on desktop');
  assert.equal(await contextRail.getByRole('link',{name:'Edit profile'}).getAttribute('href'),'/welcome?edit=1');
  await page.screenshot({path:path.join(output,'advisor-desktop.png'),fullPage:true});
  await contextRail.screenshot({path:path.join(output,'advisor-context-desktop.png')});
  const mobileContext=await context.newPage();
  await mobileContext.setViewportSize({width:320,height:900});
  await mobileContext.goto(previewUrl + '/advisor');
  const mobileRail=mobileContext.getByRole('complementary',{name:'What the advisor sees'});
  await mobileRail.locator('summary').waitFor();
  assert(!await mobileRail.locator('details').evaluate(el=>el.open),'Context starts collapsed on mobile');
  await mobileRail.locator('summary').focus();
  await mobileContext.keyboard.press('Enter');
  await mobileRail.getByRole('meter',{name:'Portfolio risk score'}).waitFor();
  assert(await mobileContext.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Expanded context fits 320px');
  await mobileRail.screenshot({path:path.join(output,'advisor-context-mobile.png')});
  await mobileRail.locator('summary').focus();
  await mobileContext.keyboard.press('Enter');
  await mobileRail.getByRole('meter').waitFor({state:'hidden'});
  await mobileContext.screenshot({path:path.join(output,'advisor-mobile.png'),fullPage:true});
  await mobileContext.close();
  await contextRail.getByRole('link',{name:'Edit profile'}).click();
  await page.getByRole('heading',{name:'Edit your profile'}).waitFor();
  await page.getByLabel('Age',{exact:true}).fill('25');
  const horizonGroup=page.getByRole('group',{name:'When might you need this money?'});
  await horizonGroup.getByRole('radio',{name:'Under 3 years',exact:true}).check();
  await page.keyboard.press('ArrowRight');
  assert(await horizonGroup.getByRole('radio',{name:'3–10 years',exact:true}).isChecked(),'Arrow keys select the next time range');
  assert(await horizonGroup.getByRole('radio').first().evaluate(el=>el.getBoundingClientRect().width===18),'Native radio indicator is visible');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.waitForURL(/\/advisor(?:\?|$)/);
  assert.equal(profileWrites.length,0,'Cancel never saves');
  await page.getByRole('complementary',{name:'What the advisor sees'}).getByRole('link',{name:'Edit profile'}).click();
  await page.getByRole('heading',{name:'Edit your profile'}).waitFor();
  assert.equal(await page.getByLabel('Age',{exact:true}).inputValue(),'24','Cancel discards the draft');
  assert(await page.getByRole('radio',{name:'10+ years',exact:true}).isChecked(),'Original horizon remains selected');
  await page.getByLabel('Age',{exact:true}).fill('25');
  await page.getByRole('radio',{name:'Under 3 years',exact:true}).check();
  await page.getByRole('radio',{name:/^High /}).check();
  await page.screenshot({path:path.join(output,'profile-edit-desktop.png'),fullPage:true});
  await page.setViewportSize({width:320,height:900});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Profile edit fits 320px');
  await page.getByRole('button',{name:'Save profile',exact:true}).scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,'profile-edit-mobile.png'),fullPage:true});
  profileSaveMode='error';
  await page.getByRole('button',{name:'Save profile',exact:true}).click();
  await page.getByText('Something went wrong on our side.',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('Age',{exact:true}).inputValue(),'25','Failed save retains edits');
  profileSaveMode='ok';
  await page.getByRole('button',{name:'Save profile',exact:true}).click();
  await page.waitForURL(/\/advisor(?:\?|$)/);
  assert.equal(profileWrites.length,2,'A failed save and its explicit retry make two writes');
  assert.deepEqual(profileWrites[1],{age:25,horizon:'short',riskTolerance:'high',goals:['retire early','buy a house']},'New labels preserve the API values');
  const directEditor=await context.newPage();
  await directEditor.goto(previewUrl + '/welcome?edit=1');
  await directEditor.getByRole('button',{name:'Cancel',exact:true}).click();
  await directEditor.waitForURL('**/portfolio');
  await directEditor.close();

  await page.goto(previewUrl + '/welcome'); await page.getByRole('heading',{name:'Tell us about your situation'}).waitFor();
  await page.setViewportSize({width:320,height:900});
  for(const route of ['/advisor','/welcome','/learn','/markets']) {
    await page.goto(previewUrl+route);
    await page.getByRole('heading',{level:1}).waitFor();
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow on ${route} at 320px`);
  }
  await page.goto(previewUrl + '/learn');
  await page.getByRole('searchbox',{name:'Search investing terms'}).fill(' ETF ');
  await page.getByText('1 term found',{exact:true}).waitFor();
  await page.locator('summary').filter({hasText:/^ETF$/}).click();
  await page.getByText('An exchange-traded fund pools investments and has shares that trade on an exchange.').waitFor();
  await page.getByRole('searchbox',{name:'Search investing terms'}).fill('zzzz');
  await page.getByRole('button',{name:'Clear search'}).click();
  await page.getByText(/^\d+ terms to explore$/).waitFor();
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>new Promise(resolve=>{window.scrollTo(0,0);requestAnimationFrame(()=>requestAnimationFrame(resolve))}));
  await page.screenshot({path:path.join(output,'learn-desktop.png'),fullPage:true});
  await page.goto(previewUrl + '/learn/what-is-investing');
  for(let i=0;i<3;i++) await page.getByRole('button',{name:/^(Continue|Check what you learned)$/}).click();
  await page.getByRole('button',{name:/Investing can grow more/}).click();
  await page.getByText('Nice, that’s right.').waitFor();
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('button',{name:/It is a warning sign/}).click();
  await page.getByRole('button',{name:'Finish lesson'}).click();
  await page.getByRole('heading',{name:'Lesson complete'}).waitFor();
  await page.getByText('You got 2 of 2 questions right. Great work.').waitFor();
  await page.goto(previewUrl + '/learn'); await page.getByText('1 of 12 lessons done').waitFor();
  await page.getByRole('button',{name:'Flashcards'}).click(); await page.getByRole('button',{name:'Reveal meaning'}).click();
  await page.getByRole('button',{name:'I knew it'}).click(); await page.getByText(/1 marked as known/).waitFor();
  await page.getByRole('button',{name:'Browse'}).click();
  holdingsMode='empty'; await page.goto(previewUrl + '/portfolio');
  await page.getByText('This account has no holdings yet. Your investments will appear here.').waitFor();
  holdingsMode='unlinked'; await page.reload(); await page.getByRole('button',{name:'Link account',exact:true}).waitFor();
  profileMode='new'; await page.goto(previewUrl + '/portfolio'); await page.reload();
  await page.getByText('What is a portfolio?',{exact:true}).waitFor();
  assert(!page.url().endsWith('/welcome'),'Portfolio introduction is public');
  await page.goto(previewUrl + '/welcome');
  await page.getByRole('link',{name:'Explore first',exact:true}).click();
  await page.getByRole('heading',{name:'Investing starts with understanding.'}).waitFor();
  await page.goto(previewUrl + '/markets');
  await page.getByRole('heading',{name:'Markets & research'}).waitFor();
  assert(!page.url().endsWith('/welcome'),'Research is available before profile setup');
  assert.deepEqual(plaidRequests,[],'Plaid SDK must not load before the user requests linking');
  profileMode='ok'; holdingsMode='unlinked';
  await context.route('https://cdn.plaid.com/link/v2/stable/link-initialize.js',route=>route.fulfill({contentType:'application/javascript',body:"window.Plaid={create:function(config){return {open:function(){config.onSuccess('public-test-token',{})},exit:function(){},destroy:function(){}}}};"}));
  await page.goto(previewUrl + '/portfolio');
  await page.getByRole('button',{name:'Link account',exact:true}).click();
  await page.locator('[data-private-value]').waitFor();
  assert(plaidRequests.length>0,'Explicit linking loads Plaid');
  assert(requests.some(url=>url==='/plaid/exchange'),'Link success exchanges the public token');
  assert.deepEqual(errors,[]);
  console.log('PASS: light-only theme; chart, keyboard, table, range; holdings search and research links; validation; provider error/retry; stale/empty history; 320/390/768 layouts; advisor prefill; onboarding; empty/unlinked holdings. Bundled SamsungOne, landscape, logo removal, automatic local-time greeting, profile radios/cancel/save/retry, persistent privacy, glossary, starter lesson/quiz/progress, flashcards and pre-profile access verified. No page errors.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
