const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const yaml = require('js-yaml');
const url = process.env.CLEARVEST_PREVIEW_URL || 'http://127.0.0.1:5173';
const output = path.resolve(__dirname, '../node_modules/.cache/clearvest-review');
const contract = yaml.load(fs.readFileSync(path.resolve(__dirname, '../../docs/api/openapi.yaml'), 'utf8'));
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || undefined, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    let release, fail = false, calls = 0;
    const errors = [];
    await context.route('http://127.0.0.1:4010/**', async route => {
      const pathname = new URL(route.request().url()).pathname;
      let status = 200;
      let body = contract.paths[pathname]?.[route.request().method().toLowerCase()]?.responses?.['200']?.content?.['application/json']?.example || {};
      if (pathname === '/advisor/chat') {
        calls++;
        await new Promise(resolve => { release = resolve; });
        status = fail ? 502 : 200;
        body = fail ? { error: { code: 'UPSTREAM_UNAVAILABLE', message: 'Unavailable' } } : { reply: '**Diversification** means spreading investments across different holdings.', disclaimer: 'Educational information, not financial advice.' };
      }
      await route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(body) });
    });
    const page = await context.newPage();
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(url);
    const companion = page.getByRole('complementary', { name: 'Scout companion' });
    const launcher = companion.getByRole('button', { name: 'Ask Scout', exact: true });
    await launcher.waitFor();
    await launcher.locator('[data-loaded="true"]').waitFor();
    const continuousGaze = await launcher.locator('svg').evaluate(el => {
      const animation = el.getAnimations({ subtree: true }).find(a => a.animationName?.includes('gaze'));
      if (!animation) return false;
      animation.pause();
      animation.currentTime = 3500;
      const first = new DOMMatrix(getComputedStyle(animation.effect.target).transform).m41;
      animation.currentTime = 4200;
      const second = new DOMMatrix(getComputedStyle(animation.effect.target).transform).m41;
      animation.currentTime = 0;
      animation.play();
      return first < 0 && first > -12 && second < first && second > -12;
    });
    assert(continuousGaze, 'Pupils interpolate through intermediate positions, not sprite frames');
    const homeScout = await launcher.elementHandle();
    const bounds = await launcher.boundingBox();
    assert(bounds.x > 1200 && bounds.y > 800, 'Scout sits at bottom right');
    assert(Math.abs(bounds.y + bounds.height - 1000) < 2, 'Launcher rests on desktop edge');
    assert.equal(await launcher.locator('svg').getAttribute('data-pose'), 'peek');
    const body = launcher.locator('svg > g').first();
    const restingY = await body.evaluate(el => new DOMMatrix(getComputedStyle(el).transform).m42);
    await launcher.hover();
    await page.waitForTimeout(150);
    const movingY = await body.evaluate(el => new DOMMatrix(getComputedStyle(el).transform).m42);
    assert(movingY > 0 && movingY < restingY, 'Body rises through intermediate positions');
    await page.waitForTimeout(500);
    assert.equal(await launcher.locator('svg').getAttribute('data-pose'), 'listen');
    assert(Math.abs(await body.evaluate(el => new DOMMatrix(getComputedStyle(el).transform).m42)) < 1, 'Listening reveals the torso');
    await page.screenshot({path:path.join(output,'scout-listen-glass.png')});
    await page.mouse.move(100, 100);
    await page.waitForTimeout(600);
    assert.equal(await launcher.locator('svg').getAttribute('data-pose'), 'peek');
    assert.equal(await launcher.getByText('BETA', { exact: true }).count(), 0, 'Resting mascot has no badge');
    await launcher.click();
    const bounce = await homeScout.evaluate(el => {
      const a = el.getAnimations({subtree:true}).find(a => a.animationName?.includes('greet'));
      if (!a) return null;
      a.pause();
      const scales = [0,134.4,326.4,480].map(t => { a.currentTime=t; const m = new DOMMatrix(getComputedStyle(a.effect.target).transform); return {scale:m.a,y:m.m42}; });
      a.finish();
      return scales;
    });
    assert(bounce && bounce[1].scale < .96 && bounce[1].y > 6 && bounce[2].y < -3 && bounce[2].scale > 1.02 && Math.abs(bounce[3].scale-1)<.001, 'Opening dips down, rises up and settles');
    const input = page.getByRole('textbox', { name: 'Your question for Scout' });
    assert(await input.evaluate(el => el === document.activeElement));
    assert.equal(calls, 0, 'Opening Scout does not call AI');
    await input.fill('Explain diversification');
    for (const tab of ['Portfolio', 'Markets', 'Learn', 'Home']) {
      await page.getByRole('navigation', { name: 'Primary' }).first().getByRole('link', { name: tab, exact: true }).click();
      assert.equal(await input.inputValue(), 'Explain diversification', 'Draft survives route changes');
      assert(await homeScout.evaluate(el => el.isConnected), 'Launcher persists outside route outlet');
    }
    const panel = page.getByRole('dialog', { name: 'Ask Scout' });
    await page.screenshot({ path: path.join(output, 'scout-home-desktop.png') });
    await page.getByRole('button', { name: 'Send to Scout' }).click();
    await companion.locator('[data-state="thinking"]').waitFor();
    await page.waitForTimeout(350);
    const thinkingEyes = companion.locator('[data-art="think"] > g').first();
    const eyeBefore = await thinkingEyes.evaluate(el => Array.from(el.querySelectorAll('g')).map(g=>getComputedStyle(g).transform));
    await page.waitForTimeout(250);
    assert.deepEqual(await thinkingEyes.evaluate(el => Array.from(el.querySelectorAll('g')).map(g=>getComputedStyle(g).transform)), eyeBefore, 'Thinking gaze and eyelids stay static');
    assert.equal(calls, 1);
    await page.keyboard.press('Enter');
    assert.equal(calls, 1, 'No duplicate request while pending');
    await page.getByRole('navigation', { name: 'Primary' }).first().getByRole('link', { name: 'Markets', exact: true }).click();
    release();
    await panel.getByText('Reply ready.', { exact: true }).waitFor();
    await companion.locator('[data-state="ready"]').waitFor();
    await input.fill('Keep this draft');
    await page.getByRole('link', { name: 'Open full Advisor' }).click();
    assert.equal(await page.getByRole('textbox', { name: 'Your question', exact: true }).inputValue(), 'Keep this draft');
    assert.equal(await companion.count(), 0, 'No floating Scout on Advisor');
    await page.getByRole('button', { name: 'Ask Scout a question' }).click();
    assert(await page.getByRole('textbox', { name: 'Your question', exact: true }).evaluate(el => el === document.activeElement));
    await page.getByText('means spreading investments across different holdings.', { exact: false }).waitFor();
    await page.screenshot({ path: path.join(output, 'scout-advisor-refined.png') });
    await page.getByRole('navigation', { name: 'Primary' }).first().getByRole('link', { name: 'Portfolio', exact: true }).click();
    await launcher.click();
    assert.equal(await input.inputValue(), 'Keep this draft');
    fail = true;
    await page.getByRole('button', { name: 'Send to Scout' }).click();
    await companion.locator('[data-state="thinking"]').waitFor();
    await page.waitForTimeout(100); release();
    await companion.locator('[data-state="unavailable"]').waitFor();
    await panel.getByRole('button', { name: 'Edit question' }).click();
    assert.equal(await input.inputValue(), 'Keep this draft', 'Recovery preserves the failed question');
    await page.screenshot({ path: path.join(output, 'scout-error-navy.png') });
    await input.fill('');
    fail = false;
    await panel.getByRole('button', { name: 'Retry', exact: true }).click();
    await companion.locator('[data-state="thinking"]').waitFor();
    await page.waitForTimeout(100); release();
    await companion.locator('[data-state="ready"]').waitFor();
    assert.equal(calls, 3);
    assert.equal(await page.getByRole('button', { name: 'Quiet motion' }).count(), 0);
    assert.equal(await page.getByRole('button', { name: 'Minimize Scout' }).count(), 0);
    await panel.getByText('BETA', {exact:true}).waitFor();
    const info = panel.getByRole('img', {name:'About Scout'});
    await info.hover();
    await panel.getByRole('tooltip').waitFor();
    await info.focus();
    await page.keyboard.press('Escape');
    await panel.getByRole('tooltip').waitFor({state:'hidden'});
    assert(await panel.isVisible(), 'Escape dismisses information before the conversation');
    await input.focus();
    await page.keyboard.press('Escape');
    assert(await launcher.evaluate(el => el === document.activeElement), 'Escape restores launcher focus');
    await page.reload();
    await launcher.click();
    await page.emulateMedia({ reducedMotion: 'reduce' });
    assert.equal(await companion.locator('[data-state]').evaluate(el => el.getAnimations({ subtree: true }).length), 0);
    await page.setViewportSize({ width: 320, height: 800 });
    const box = await panel.boundingBox();
    assert(box.x >= 0 && box.x + box.width <= 320 && box.y >= 0 && box.y + box.height < 736, 'Panel fits above mobile navigation');
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    const subtitle = panel.getByText('A little clarity, whenever you need it.', {exact:true});
    assert(await subtitle.evaluate(el => el.scrollWidth <= el.clientWidth && getComputedStyle(el).whiteSpace === 'nowrap'), 'Full subtitle fits on one line at 320px');
    await page.screenshot({ path: path.join(output, 'scout-mobile-open.png') });
    // Simulate a mobile visual viewport shrinking for the on-screen keyboard.
    await page.evaluate(() => {
      Object.defineProperty(window.visualViewport, 'height', { configurable: true, value: 420 });
      window.visualViewport.dispatchEvent(new Event('resize'));
    });
    await page.waitForFunction(() => document.querySelector('[data-keyboard="true"]'));
    const keyboardPanel = await panel.boundingBox();
    const keyboardInput = await input.boundingBox();
    assert(keyboardPanel.y >= 0 && keyboardPanel.y + keyboardPanel.height <= 420, 'Panel fits the keyboard visual viewport');
    assert(keyboardInput.y >= 0 && keyboardInput.y + keyboardInput.height <= 420, 'Keyboard does not obscure composer');
    await page.evaluate(() => {
      delete window.visualViewport.height;
      window.visualViewport.dispatchEvent(new Event('resize'));
    });

    await page.getByRole('button', { name: 'Close Scout', exact: true }).click();
    await page.mouse.move(100, 100);
    await page.waitForTimeout(600);
    assert.equal(await launcher.locator('svg').getAttribute('data-pose'), 'peek', 'Closing with the mouse restores the resting peek');
    const mobileBounds = await launcher.boundingBox();
    assert(mobileBounds.x >= 200 && mobileBounds.y + mobileBounds.height <= 736, 'Mobile launcher clears nav');
    await page.screenshot({ path: path.join(output, 'scout-mobile-peek.png') });
    await page.goto(url + '/learn');
    const lesson = page.locator('a[href^="/learn/"]').first();
    await lesson.click();
    await launcher.waitFor();
    await page.goto(url + '/welcome');
    assert.equal(await companion.count(), 0);
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('PASS: all companion routes; persistent launcher/draft/thread; Advisor handoff; focus/Escape; pending/retry/deduplication; peek/listen/think/ready; torso rise; popup-only beta label; opening bounce; hover info; reduced motion; 320px placement; no page errors.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
